### ISSUE TITLE
Update Radio buttons to unique bool buttons

### ISSUE THREAD

**Issue by Zugyuk** [SteveWorcester/Roll20Roller#13]
Make them bigger and easier to spot.

Colorize the clicked buttons based on the type of radio selected.

Advantage = Green
Normal = Dark Grey
Disadvantage = Red

**Comment by SteveWorcester** [comment]
- Colorized buttons should be permanent, not on activation.
- The selected advantage should change the entire form background to the associated advantage color to make the selected advantage more easily notacable (before rolling)
