### ISSUE TITLE
Straight stat checks

### ISSUE THREAD

**Issue by EdSlunka** [SteveWorcester/Roll20Roller#32]
Maybe a drop down to choose stat check or saving throw

**Comment by SteveWorcester** [comment]
This can be handled by a checkbox for a true/false situation; i think this would be a lighter-weight option for selection. do you have other preferences for UI on this?

Would you expect any kind of UI warning when this option is selected? what kind of warning would you expect?

After clicking the stat button and the template copies to your clipboard, would you expect the checkbox status to be reset to roll saving throws again, or would you expect to have stat checks activated until manually deactivated?
